/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class OCR_server_AthleteOCR */

#ifndef _Included_OCR_server_AthleteOCR
#define _Included_OCR_server_AthleteOCR
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     OCR_server_AthleteOCR
 * Method:    getAthleteNumber
 * Signature: ([D)I
 */
JNIEXPORT jint JNICALL Java_OCR_1server_AthleteOCR_getAthleteNumber
  (JNIEnv *, jclass, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
